print("\n")
print("Practice 4:")
print("Tuple Basics")
print("1. Create a tuple containing the names of five continents.")
print("2. Print the third continent in the tuple.")
print("3. Try to change the second continent and observe the result.")
print("\n")
continents=("Asia", "Africa", "America","Antarctica", "Europe")
print("Five Continents name in tuple :- ",continents)
print("Third Continents list :- ",continents[2])
print("Error: tuples are not change ")
