print("\n")
print("Practice 7:")
print("Set Operations")
print("1. Create a set of the first five odd numbers.")
print("2. Create another set of the first five even numbers.")
print("3. Find the union and intersection of these sets.")
print("4. Print the results.")
print("\n")
print("odd number :- ")
odd={1,3,5,7,9}
print(odd)
print("even number :- ")
even={2,4,6,8,10}
print(even)
Union_set=odd.union(even)
intersection_set=odd.intersection(even)
print("Union Set :- ")
print(Union_set)
print("Intersection Set :- ")
print(intersection_set)
