print("\n")
print("Practice 4:")
print("Tuple Basics")
print("1. Create a tuple containing the names of five continents.")
print("2. Print the third continent in the tuple.")
print("3. Try to change the second continent and observe the result.")
print("\n")
fruit=("apple","mango","grape","banana","lichi")
print("Five fruit name in tuple :- ",fruit)
print("Third continet list :- ",fruit[2])
print("Error: tupes are not change ")